# DEV Environments
# ----------------------------DEV Environments Details----------------------
env                           =      dev
browser                       =      chrome
url                           =      https://kuby-private.vercel.app/en/signin
loginUserEmail                 =     naspoorisandeep844+test3@gmail.com
loginPassword                 =      Password@123
#New_Password                  =      Password@123
#ProfileImagePath              =      \\TestDataDocs\\userPhoto.png
#Profile_Name                  =      Test_Sandeep Kumar
#Organization_Address_country  =      India
#Organization_Address_State    =      Maharashtra
##-----------------------Decommision API End Point ---------------------------
#DecommisionEndPointUrl        =      https://gt2ufjbofl.execute-api.ap-south-1.amazonaws.com/api/decommission-all-test-inventory
#LoginDevEnvAPI                =      https://gt2ufjbofl.execute-api.ap-south-1.amazonaws.com/api/user/login
##------------- E-Mail Configuration -----------------------------------------
senderEmailAddress            =      naspoorisandeep844+test3@gmail.com
senderEmailPassword           =      nbup ovrg zvev wgyg
receiverEmailAddress          =      naspoorisandeep844@gmail.com